### ISSUE TITLE
"Internal Server Error" when search for any french city

### ISSUE THREAD

**Issue by Christian-Martins** [Hunam6/Goodgle#2]
Here's a vid with the problem, same on the demo website
https://user-images.githubusercontent.com/35039147/119178495-58d4d480-ba5d-11eb-8c95-4946ae8c9a5f.mp4

**Comment by Hunam6** [comment]
Thanks for reporting, I rewritten spell checking / no results code, it should work, let me know if it does

**Comment by Christian-Martins** [comment]
Works like a charm!
